# Generated by Django 4.0.1 on 2022-07-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('option1', models.CharField(default='', max_length=10)),
                ('option2', models.CharField(default='', max_length=10)),
                ('option3', models.CharField(default='', max_length=10)),
                ('option4', models.CharField(default='', max_length=10)),
                ('option5', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
