# Generated by Django 4.0.1 on 2022-07-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tag_alter_question_option1_alter_question_option2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
