# Generated by Django 4.0.1 on 2022-07-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_question_tags_delete_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.CharField(default='', max_length=50),
        ),
    ]
