# Generated by Django 4.0.1 on 2022-07-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_question_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
